export const dummyVideos = [
  {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://img.youtube.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/Ke90Tje7VS0",
    description: "Quick tutorial to get started with React.",
    channelId: "channel01",
    uploader: "user01",
    views: 15200,
    likes: 1200,
    dislikes: 40,
    uploadDate: "2024-04-01",
    comments: [
      {
        commentId: "comment01",
        userId: "user02",
        text: "Really helpful video!",
        timestamp: "2024-04-02T08:30:00Z",
      },
    ],
  },
  {
    videoId: "video02",
    title: "Master Node.js in One Hour",
    thumbnailUrl: "https://img.youtube.com/vi/TlB_eWDSMt4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/TlB_eWDSMt4",
    description: "Learn backend development using Node.js quickly.",
    channelId: "channel02",
    uploader: "user03",
    views: 9800,
    likes: 850,
    dislikes: 20,
    uploadDate: "2024-04-02",
    comments: [
      {
        commentId: "comment02",
        userId: "user04",
        text: "Simple and clear explanation.",
        timestamp: "2024-04-03T08:45:00Z",
      },
    ],
  },
  {
    videoId: "video03",
    title: "Understanding MongoDB in 20 Minutes",
    thumbnailUrl: "https://img.youtube.com/vi/0e3GPea1Tyg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/0e3GPea1Tyg",
    description: "MongoDB crash course for beginners.",
    channelId: "channel03",
    uploader: "user05",
    views: 7400,
    likes: 600,
    dislikes: 10,
    uploadDate: "2024-04-03",
    comments: [
      {
        commentId: "comment03",
        userId: "user06",
        text: "Loved the examples!",
        timestamp: "2024-04-04T10:20:00Z",
      },
    ],
  },
  {
    videoId: "video04",
    title: "CSS Grid Tutorial for Beginners",
    thumbnailUrl: "https://img.youtube.com/vi/jV8B24rSN5o/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/jV8B24rSN5o",
    description: "Complete guide to CSS Grid Layout.",
    channelId: "channel01",
    uploader: "user01",
    views: 5400,
    likes: 430,
    dislikes: 15,
    uploadDate: "2024-04-04",
    comments: [
      {
        commentId: "comment04",
        userId: "user07",
        text: "Best CSS grid explanation!",
        timestamp: "2024-04-05T11:15:00Z",
      },
    ],
  },
  {
    videoId: "video05",
    title: "JavaScript Array Methods Crash Course",
    thumbnailUrl: "https://img.youtube.com/vi/R8rmfD9Y5-c/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/R8rmfD9Y5-c",
    description: "Learn important array methods in JavaScript.",
    channelId: "channel02",
    uploader: "user03",
    views: 8700,
    likes: 760,
    dislikes: 25,
    uploadDate: "2024-04-05",
    comments: [
      {
        commentId: "comment05",
        userId: "user08",
        text: "Awesome crash course!",
        timestamp: "2024-04-06T09:00:00Z",
      },
    ],
  },
];
